name: Run PHPUnit Tests and Deploy

on:
  push:
    branches:
      - main

jobs:
  run_phpunit_tests:
    name: Run PHPUnit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-

      - name: Setup PHP with required extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit tests

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: run_phpunit_tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: files.000webhost.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/
          log-level: verbose  # Increase log level to verbose
          dangerous-clean-slate: true  # Ensure the remote directory is cleaned before upload
          exclude: |
            **/.git*
            **/.git*/**
            node_modules/**
            **/node_modules/**
