name: Deploy, Diagnose, and Test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: files.000webhost.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/
          log-level: verbose
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/.git*/**
            node_modules/**
            **/node_modules/**

      - name: Verify deployment
        run: |
          curl -I https://tu-sitio-web.com/index.php  # Reemplaza con la URL de tu sitio web
          curl -I https://tu-sitio-web.com/ruta-a-un-archivo.php  # Reemplaza con la URL de un archivo PHP específico

  diagnose:
    name: Diagnose PHP issues
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List directory contents
        run: ls -al

      - name: Display PHP version
        run: php -v

      - name: Display PHP configuration
        run: php -i

  test:
    name: Run PHPUnit Tests
    runs-on: ubuntu-20.04
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-

      - name: Setup PHP with required extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit tests
